fix #40 allow ?thanks without for and/or without message
kentcdodds/kcd-discord-bot-v1 pull request #42
Opened 2020-12-24 13:34 UTC by Aprillion

**What**: fixing #40 by allowing ?thanks command without `for` and/or without message

**Why**: 

**How**:

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged

2020-12-24 13:56 UTC, Aprillion commented on src/commands/command-fns/thanks.js
> -    .replace(/^.*?for/, '')
FTR: MessageMentions.USERS_PATTERN is `/<@!?(\d{17,19})>/g` => it did not do any replacement itself, all was done by the second regexp, `/^.*?for/`, in the deleted code

2020-12-26 09:25 UTC, marcosvega91 requested changes
Hi @Aprillion thanks for working on this :). It's awesome :). I have left two small comments, let me know what you think

2020-12-26 09:25 UTC, marcosvega91 commented on src/commands/command-fns/__tests__/thanks.js
> +})
I think that when there is no message we can simply say 

```
Hey <@123>! You got thanked by <@123>! 🎉
Link: <https://discordapp.com/channels/123/123/123>
```

what do you think?

2020-12-26 09:25 UTC, marcosvega91 commented on src/commands/command-fns/thanks.js
> -    .replace(/^.*?for/, '')
When you mention someone the message will contain something similar to `<@1233435454546563>`.

Your regex will work but I prefer what we already have. 

1. `.replace(MessageMentions.USERS_PATTERN, '')` will remove the mentioned user
2. `.replace(/^.*?for/, '')` will remove the text before `for` if is present.

2020-12-26 10:00 UTC, Aprillion commented on src/commands/command-fns/__tests__/thanks.js
> +})
That sounds reasonable, not sure when I will find time to dig into that part of code deeper. Maybe today or next week.

2020-12-26 10:07 UTC, Aprillion commented on src/commands/command-fns/thanks.js
> -    .replace(/^.*?for/, '')
Could you please update the unit tests so they reflect the situation you are describing?

Since the regex did not match in the test, I have no idea what exactly do you mean :(

e.g. `await setup('?thanks @user1 for the help with epicReact', ['user1'])` does not contain `<@1233435454546563>` so the regex 1. is a no-op and regex 2. was doing all the work in that test case

2020-12-26 10:50 UTC, smeijer commented on src/commands/command-fns/__tests__/thanks.js
> +})
@marcosvega91 , what do you think about this one in case a `for` is present:

(current state)
```
    "Hey <@123>! You got thanked! 🎉

    <@123> appreciated you for:

    > 👍

    Link: <https://discordapp.com/channels/123/123/123>"
```

And this one for when there is no `for`:

```
    "Hey <@123>! You got thanked! 🎉

    <@123> appreciates you.

    Link: <https://discordapp.com/channels/123/123/123>"
```

I think it shows a bit more gratitude than your variant.

2020-12-26 15:27 UTC, Aprillion commented on src/commands/command-fns/__tests__/thanks.js
> +})
now fixed, using Stephan's suggestion.

2020-12-27 16:25 UTC, marcosvega91 commented on src/commands/command-fns/__tests__/thanks.js
> +})
yes I like his suggestion, thanks guys

2020-12-27 16:55 UTC, marcosvega91 commented on src/commands/command-fns/thanks.js
> -    .replace(/^.*?for/, '')
Yes I understand what you mean. The problem here is that the `discord` client will replace the `@user1` with `<@1233435454546563>` where `1233435454546563` is the user id. If you look at the `private-chat` test file in the setup function I have built the content dynamically 

https://github.com/kentcdodds/kcd-discord-bot/blob/e18b7a13b9abf1e814df98feb019531db4eaf3b6/src/commands/command-fns/__tests__/private-chat.js#L23-L30

I think that we can update the `setup` function as

```js
async function setup(content, mentionedUsernames = []) {
  const {client, defaultChannels, kody, createUser} = await makeFakeClient()
  const mentionedUsers = (
    await Promise.all(mentionedUsernames.map(username => createUser(username)))
  ).map(guildMember => guildMember.user)

  const message = new Discord.Message(
    client,
    {
      id: SnowflakeUtil.generate(),
      content: content.replace(/\@(\S+)/, (_, mention) =>
        mentionedUsers.find(user => user.username === mention),
      ),
      author: kody.user,
    },
    defaultChannels.talkToBotsChannel,
  )

  Object.assign(message, {
    mentions: new Discord.MessageMentions(message, mentionedUsers, [], false),
  })

  const getBotMessages = () =>
    Array.from(defaultChannels.talkToBotsChannel.messages.cache.values())
  const getThanksMessages = () =>
    Array.from(defaultChannels.thanksChannel.messages.cache.values())
  return {
    getBotMessages,
    getThanksMessages,
    mentionedUsers,
    kody,
    botChannel: defaultChannels.talkToBotsChannel,
    thanksChannel: defaultChannels.thanksChannel,
    message,
    createUser,
  }
}
```

2020-12-27 17:08 UTC, Aprillion commented on src/commands/command-fns/thanks.js
> -    .replace(/^.*?for/, '')
perfect, thanks for the setup function!

PR updated, diff can be found in the force push link if you want to see just the last change: https://github.com/kentcdodds/kcd-discord-bot/compare/09fe25a6cf7aa2d2334a8265d9096aba4771e6ac..906dee2ff9080a4c58bd35ed8991ab6b4eb3be58

2020-12-27 18:23 UTC, marcosvega91 approved these changes
For me is nice :) thanks @Aprillion

2020-12-27 18:34 UTC, kentcdodds approved these changes
Super! Thank you 👏👏

2020-12-27 18:34 UTC, merged

2020-12-27 18:35 UTC, kentcdodds commented
@all-contributors please add @Aprillion for code and tests